name: CI

on:
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check:
    runs-on: [self-hosted, kstest]

    steps:
      - name: Checkout change
        uses: actions/checkout@v2
        with:
          path: tclib

      - name: Clone test repository
        run: |
          git clone --depth 1 ${{ secrets.TEST_REPO }} tests

      - name: Build container
        run: |
          podman build -t tclib -f $GITHUB_WORKSPACE/tests/Containerfile

      - name: Run tests
        run: |
          podman run --rm -e TCLIB=/root/tclib \
                     -v $GITHUB_WORKSPACE/tclib:/root/tclib:Z \
                     -v $GITHUB_WORKSPACE/tests:/root/tests:Z \
                     -w /root/tests tclib ./run_tests.sh

      - name: Build documentation
        run: |
          podman run --rm \
                     -v $GITHUB_WORKSPACE/tclib:/root/tclib:Z \
                     -w /root/tclib/doc \
                     tclib make html

      - name: Cleanup
        if: always()
        run: |
          rm -rf $GITHUB_WORKSPACE/tests
          podman rmi -f tclib
